config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'dashboard#show'

  resources :users do
    post '/start-crawling', to: 'crawls#crawl_website'
    resources :activities, only: [:index]
    resources :crawls, only: [:show] do
      member do
        get '/export-crawl', to: 'crawls#export_crawl'
      end
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :crawl
  belongs_to :user

  validates_uniqueness_of :crawl_id, scope: :user_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crawl.rb
class Crawl < ApplicationRecord
  extend FriendlyId
  friendly_id :url, use: :slugged

  belongs_to :user

  validates :url, presence: true
  validates :products, presence: true

  serialize :products, Array
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :first_name, use: :slugged

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :crawls
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @activities = ActivitiesDecorator.decorate(current_user.activities.includes(:crawl).reverse)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :layout_by_resource

  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def layout_by_resource
    if signed_in?
      'application'
    else
      'home'
    end
  end

  def after_sign_in_path_for(resource)
    ApplicationMailer.sign_in_mail(current_user).deliver
    dashboard_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |parameter|
      parameter.permit(:first_name, :last_name, :gender, :email, :password)
    end
  end
end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_crawl, only: [:show, :export_crawl]

  def crawl_website
    Crawl::CrawlWebsite.call(self, current_user, params)
  end

  def show
  end

  def export_crawl
    file, file_type, filename = Exports::Excel::CrawlInfo.generate(@crawl)
    ApplicationMailer.mail_admin(current_user, @crawl).deliver
    send_file file.path, filename: filename, type: file_type, disposition: "attachment"
  end

  private

  def find_crawl
    @crawl = Crawl.find_by_slug(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
    @crawl = Crawl.new
    @activities = ActivitiesDecorator.decorate(current_user.activities.includes(:crawl).last(30).reverse)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    user_signed_in? ? dashboard_path : root_path
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<%= render partial: 'shared/activities', locals: { activities: @activities } %>

app/views/crawls/_crawls.html.erb
<h2> Below are the crawling details </h2>
<div class="table-responsive">
  <table class="table table-bordered table-inverse">
    <tr>
      <td class = 'bold-font'>Crawl Created Time</td>
      <td ><%= crawl.created_at %></td>
       <td> </td>
    </tr>
    <tr>
      <td class = 'bold-font'>Crawled URL</td>
      <td ><%= crawl.url %></td>
       <td> <%= link_to 'Click Here to Crawl Again',  user_start_crawling_path(current_user, crawl: {url: crawl.url}), method: 'post'%></td>
      </tr>
    <tr>
      <td class = 'bold-font'>Total Products crawled</td>
      <td > <%= crawl.products.length %> </td>
       <td>
        <%= link_to 'Click Here to Export Crawl', export_crawl_user_crawl_path(current_user, crawl.slug), method: 'get'%></td>
     </td>
    </tr>
  </table>
</div>
<% if crawl.products.length == 1 %>
  <%= render partial: 'product', locals: { crawl: crawl } %>
<% else %>
  <%= render partial: 'products', locals: { crawl: crawl } %>
<% end %>

app/views/crawls/_product.html.erb
<div class="col-md-2 col-sm-2 col-xs-4"></div>
  <div class="col-md-8 col-sm-10 col-xs-8">
      <div class="table-responsive">
        <table class="table table-bordered table-inverse">
        <% crawl.products.each_with_index do |product, index| %>
          <div style="margin-bottom: 50px">
            <tr>
              <td class = 'bold-font'>Title</td>
              <td> <%= product[:title] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Actual Price</td>
              <td> <%= product[:actual_price] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Offer Price</td>
              <td> <%= product[:offer_price] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Offer Percentage</td>
              <td> <%= product[:offer_percentage] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>EMI </td>
              <td> <%= product[:emi] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Ratings</td>
              <td> <%= product[:ratings] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Reviews</td>
              <td> <%= product[:reviews] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Extra Offers</td>
              <td> <%= product[:extra_offers] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Delivery In</td>
              <td> <%= product[:delivery_in] %> </td>
            </tr>
            <tr>
              <td class = 'bold-font'>Image Url</td>
              <td> <a href = "<%= product[:image] %>" target = '_blank'><%= product[:image] %> </a></td>
            </tr>
          </div>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/crawls/_products.html.erb
<div class="col-md-2 col-sm-2 col-xs-4"></div>
  <div class="col-md-8 col-sm-10 col-xs-8">
    <h4> Here are the list of products crawled </h4>
    <div class="table-responsive" style='margin-bottom: 50px'>
      <% crawl.products.each_with_index do |product, index| %>
        <table class="table table-bordered table-inverse">
          <tr>
            <td class = 'bold-font'>S.No</td>
            <td> <%= index + 1 %> </td>
          </tr>
          <tr>
            <td class = 'bold-font'>Title</td>
            <td> <%= product[:title] %> </td>
          </tr>
          <tr>
            <td class = 'bold-font'>Actual Price</td>
            <td> <%= product[:actual_price] %> </td>
          </tr>
          <tr>
            <td class = 'bold-font'>Offer Price</td>
            <td> <%= product[:offer_price] %> </td>
          </tr>
          <tr>
            <td class = 'bold-font'>EMI </td>
            <td> <%= product[:emi] %> </td>
          </tr>
          <tr>
            <td class = 'bold-font'>Ratings</td>
            <td> <%= product[:ratings] %> </td>
          </tr>
          <tr>
            <td class = 'bold-font'>Image Url</td>
            <td> <a href = "<%= product[:image] %>" target = '_blank'><%= product[:image] %> </a></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/crawls/show.html.erb
<%= render partial: 'crawls', locals: { crawl: @crawl } %>

app/views/dashboard/show.html.erb
<div class="container">
  <div class="row">
    <div class= "col-md-12">
      <div class="col-md-9 col-sm-8 col-xs-12 padding-0">
        <%= form_for(@crawl, url: user_start_crawling_path(current_user), html: { method: :post }) do |f| %>
          <div class="list-group">
            <div class="list-group-item">
              <%= f.text_field :url, class: 'form-control no-border', autocomplete: "off", required: true, autofocus: true,  placeholder: 'paste snapdeal products url or single product url to start crawling' %>
            </div>
          </div>
      </div>
      <div class="col-md-2 col-sm-3 col-xs-12 margin-top-5">
        <%= f.submit "Start Crawling", {class: 'btn btn-lg btn-primary btn-block bg-color'} %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class= "col-md-12">
      <%= render partial: 'shared/activities', locals: { activities: @activities } %>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<%= image_tag("panorama-HD.jpg", alt: "Mountain View", class: 'fit-page') %>

app/views/layouts/application.html.erb
<html>
<head>
  <title>
    Crawling Application
  </title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
</head>
<body>
<div class="container width-100">
  <%= render :partial => '/layouts/home/header' %>
  <div class="flash bg-success">
    <% flash.each do |type, message| %>
        <div class=" alert alert-<%= type %>">
            <span>
              <%= message %>
            </span>
          <span class="pull-right x cursor-pointer">X</span>
        </div>
    <% end %>
  </div>
  <div class="main-color" id="main-wrap">
    <%= yield %>
  </div>
</div>
<%= render :partial => '/layouts/home/footer' %>
<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/home.html.erb
<html>
<head>
  <title>
    Crawling App | home
  </title>
  <%= stylesheet_link_tag 'home' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <!--<link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">/</link>-->
  <!--<link href="<%= asset_path('fav.ico') %>" rel="shortcut icon"></link>-->
</head>
<body>
<div id="container-fluid">
  <%= render :partial => '/layouts/home/header' %>
  <div class="flash bg-danger">
    <% flash.each do |type, message| %>
        <div class=" alert alert-<%= type %>">
            <span>
              <%= message %>
            </span>
          <span class="pull-right x cursor-pointer" >X</span>
        </div>
    <% end %>
  </div>
  <div class="main-color" id="main-wrap">
    <%= yield %>
  </div>
</div>
<%= render :partial => '/layouts/home/footer' %>
<%= javascript_include_tag 'home' %>
</body>
</html>

app/views/layouts/home/_footer.html.erb
<footer>
  <div class="footer bg-color ">
    <div class="container">
      <div class="row height">
        <div class="col-md-12 col-sm-12 col-xs-12 color">
          <span>© Crawling Application  &nbsp;</span>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/home/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top bg-color">
  <div class="container navbar-color">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggle collapsed" data-target="#navbar" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand ems p-l-15">
        <a href='#'>
        <% if signed_in? %>
          <a href = '/dashboard'>
          <span class = 'font-color'> <%= current_user.first_name %></span>
          </a>
        <% else %>
          <a href = '/'>
          <span class = 'header-color'>Crawling Application</span></a>
        <% end %></a>
      </div>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <% if !signed_in? %>
        <ul class="nav navbar-nav navbar-right ems p-r-15">
          <li>
            <%= link_to 'Signin', new_user_session_path %>
          </li>
           <li>
            <%= link_to 'Signup', new_user_registration_path %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right ems p-r-15">
          <li>
          <%= link_to 'Dashboard', dashboard_path, method: 'get' %>
          </li>
          <li>
          <%= link_to 'Activities', user_activities_path(current_user.slug), method: 'get' %>
          </li>
          <li>
          <%= link_to 'Logout', destroy_user_session_path, method: 'delete' %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_activities.html.erb
<% if activities.present? %>
  <h2 class = 'margin-more-top'> Total Products Crawled: <span class='green'><%= activities.crawled_products_count %></span></h2>
  <h4 class = 'margin-top'> Recent Activities </h4>
  <div class="table-responsive">
    <table class="table table-bordered table-inverse">
      <thead>
        <tr>
          <th>S.No</th>
          <th>Time</th>
          <th>Crawled URL</th>
          <th>Total Products crawled</th>
        </tr>
      </thead>
      <tbody>
        <% activities.each_with_index do |activity, index| %>
            <tr>
              <td><%= index + 1 %></td></div>
              <td><%= activity.formatted_time(activity.created_at) %></td>
              <td> <%= link_to activity.crawl.url, user_crawl_path(current_user.slug, activity.crawl.slug) %></td>
              <td><%= activity.crawl.products.length %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class= "col-md-3"></div>
  <div class= "col-md-6 margin-20">
    <h4> You haven't started any crawling yet! </h4>
    <h4>Hurry up start crawling the snapdeal website by pasting the correct url!!</h4>
  </div>
  <div class= "col-md-3"></div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>